---
resource_types:
  - name: 'wedeploy-container-builder'
    type: 'docker-image'
    source:
      repository: '192.168.0.123:5000/wedeploy/container-builder-resource'
      insecure_registries: ['192.168.0.123:5000']

resources:
  - name: 'repository-master'
    type: 'git' 
    source:
      uri: 'https://github.com/cirocosta/test-project.git'

  - name: 'builder-resource'
    type: 'wedeploy-container-builder' 
    source:
      sample: true


jobs:
  - name: "config-builder-master"
    serial: true
    plan:
      - get: 'repository-master'
        trigger: true

      - task: 'build-config-generator'
        config: 
          platform: linux
          image_resource:
            type: docker-image
            source: 
              repository: '192.168.0.123:5000/wedeploy/build-config-generator'
              insecure_registries: ['192.168.0.123:5000']

          inputs:
            - name: 'repository-master'
              path: 'git-resource'
          outputs:
            - name: 'builder-resource'
              path: 'build-config'
          run:
            path: entrypoint

      - put: 'builder-resource'

  - name: "container-1"
    plan:
      - get: 'repository-master'
      - get: 'builder-resource'
        trigger: true
        passed: ['config-builder-master']
        params:
          index: 0
      - task: 'build-config-generator'
        config: 
          platform: linux
          image_resource:
            type: docker-image
            source: 
              repository: '192.168.0.123:5000/'
              insecure_registries: ['192.168.0.123:5000']

          inputs:
            - name: 'repository-master'
              path: 'git-resource'
            - name: 'builder-resource'
              path: 'build-config'
          run:
            path: entrypoint
