---
resources:
  - name: 'repository'
    type: 'git' 
    source:
      uri: 'https://github.com/cirocosta/concourse-experiments.git'

  - name: 'base-image'
    type: 'docker-image' 
    source:
      repository: 'frolvlad/alpine-bash'

  - name: 'image'
    type: 'docker-image' 
    source:
      repository: '192.168.108.86:5000/test/static'
      insecure_registries: ['192.168.108.86:5000']

jobs:
  - name: "build"
    plan:
      - get: 'base-image'
        params:
          save: true

      - get: 'repository'
        trigger: true

      - task: 'hue'
        image: base-image
        config: 
          platform: linux
          inputs:
            - name: 'repository'
          outputs:
            - name: 'result'
          run:
            path: "/bin/sh"
            args: 
              - '-exc'
              - 'cp -r repository/example-container/* result/'

      - put: 'image'
        get_params:
          skip_download: true
        params:
          load_base: "base-image"
          build: "result"
