---
jobs:
  - name: "myjob" 
    plan:
      - task: 'build-task'
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: 'busybox' 
            inputs:
              - name: 'repository' 
          run:
            path: pwd              

