---
resources:
  - name: 'base-image'
    type: 'docker-image' 
    source:
      repository: 'alpine:3.4'

jobs:
  - name: "sample-job"
    plan:
      - get: 'base-image'
        params:
          save: true

      - task: 'sample-task'
        image: 'base-image'
        config: 
          platform: linux
          run:
            path: pwd

