---
resource_types:
  - name: 'verbose-git'
    type: 'docker-image' 
    source:
      uri: 'cirocosta/verbose-git-resource'

resources:
  - name: 'repository'
    type: 'verbose-git' 
    source:
      uri: 'https://github.com/cirocosta/test-project.git'
      branch: master

jobs:
  - name: "myjob" 
    plan:
      - get: 'repository'
        trigger: false

      - task: 'build-task'
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: 'wedeploy/builder' 
            inputs:
              - name: 'repository' 
          run:
            path: pwd              

